rembish_org/blueprints/drone.py
from flask import Blueprint, redirect, url_for

from ..forms.flight import FlightForm
from ..libraries.database import db
from ..libraries.geonames import geonames
from ..libraries.globals import me
from ..libraries.templating import with_template, with_json
from ..models.drone import FlightLog, Takeoff
from ..models.world import Country

root = Blueprint("drone", __name__)


@root.route("/flightlog")
@with_template
def flightlog():
    flights = FlightLog.get_flights_for(me)
    stats = FlightLog.get_statistics_for(me)

    return {
        "flights": flights,
        "stats": stats,
    }


@root.route("/drones/<int:drone_id>")
@with_template
def drone(drone_id):
    pass


@root.route("/flight/<int:flight_id>")
@with_template
def flight(flight_id):
    pass


@root.route("/flight/new", methods=("GET", "POST"))
@with_template
def new_flight():
    form = FlightForm()
    if form.validate_on_submit():
        flightlog = FlightLog()
        for _ in form.takeoffs:
            flightlog.takeoffs.append(Takeoff())
        form.populate_obj(flightlog)

        code = geonames.get_code_by(flightlog.latitude, flightlog.longitude)
        if code:
            country = Country.get_by(code)
            flightlog.country = country

        db.session.add(flightlog)
        db.session.commit()

        return redirect(url_for("drone.flightlog"))

    return {
        "form": form,
    }


@root.route("/flight/takeoff", methods=("POST",))
@with_json
def takeoff():
    pass

rembish_org/templates/drone/flight.html
{% extends "layout.html" %}

rembish_org/templates/drone/flightlog.html
{% extends "layout.html" %}

{% block title %}Flight log - Alex Rembish{% endblock %}

{% block css %}
    <link href="{{ static_url('vendor/flag-icon-css/css/flag-icon.min.css') }}" rel="stylesheet">
{% endblock %}

{% block main %}
    <section class="flightlog">
        <div class="container">
            <div class="section-title">
                <h2>Drone flight log</h2>
            </div>

            <div class="row">
                {% if not current_user.has_role("administrator") %}
                <div class="col-lg-3">
                    <div class="count-box">
                        <i class="icofont icofont-ui-flight"></i>
                        <span data-toggle="counter-up">{{ stats.flight_count }}</span>
                        <p>Flight count</p>
                    </div>
                </div>
                {% endif %}
                <div class="col-lg-3">
                    <div class="count-box">
                        <b class="flaticon-target"></b>
                        <span data-toggle="counter-up">{{ stats.takeoff_count }}</span>
                        <p>Take-off count</p>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="count-box">
                        <b class="flaticon-navigation"></b>
                        <span data-toggle="counter-up">{{ "{:,.0f}".format(stats.distance / 1000) }} km</span>
                        <p>Total distance</p>
                    </div>
                </div>
                {% if current_user.has_role("administrator") %}
                <div class="col-lg-3">
                    <div class="count-box">
                        <b class="flaticon-radar"></b>
                        <span data-toggle="counter-up">{{ stats.altitude }} m</span>
                        <p>Max altitude</p>
                    </div>
                </div>
                {% endif %}
                <div class="col-lg-3">
                    <div class="count-box">
                        <i class="icofont icofont-ui-clock"></i>
                        <span data-toggle="counter-up">{{ stats.duration }}</span>
                        <p>Time in the air</p>
                    </div>
                </div>
            </div>

            {% if current_user.has_role("administrator") %}
            <div class="row">
                <a href="{{ url_for("drone.new_flight") }}">Register flight</a>
            </div>
            {% endif %}

            <div class="table-responsive"><table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col" class="align-text-top">#</th>
                        <th scope="col">Date<br><small>Take-off &ndash; Landing</small></th>
                        <th scope="col">Place<br><small>Additional information</small></th>
                        <th scope="col" class="align-text-top">Drone<br><small>Distance</small></th>
                        <th scope="col" class="align-text-top">Duration</th>
                        <th scope="col">Type<br><small>Activity</small></th>
                    </tr>
                </thead>
                <tbody>
                {% for flight in flights %}
                    <tr>
                        <th scope="row">{{ loop.index }}</th>
                        <td class="text-nowrap">
                            {{ flight.date.strftime("%d.%m.%Y") }}<br>
                            <small>{{ flight.takeoff }} &ndash; {{ flight.landing }}</small>
                        </td>
                        <td>
                            {% if flight.country_code %}
                                <span class="flag-icon flag-icon-{{ flight.country_code | lower }}" title="{{ flight.country }}"></span>
                            {% endif %}
                            <a href="{{ url_for("drone.flight", flight_id=flight.id) }}">{{ flight.location | default("Untitled") }}</a>
                            {% if flight.description %}<br><small>{{ flight.description }}</small>{% endif %}
                        </td>
                        <td>
                            <a href="{{ url_for("drone.drone", drone_id=flight.drone_id) }}">{{ flight.drone_name }}</a>
                            {% if flight.distance %}<br><small>{{ flight.distance }} m</small>{% endif %}
                        </td>
                        <td>
                            {{ flight.duration }}
                            {% if flight.landing_count > 1 %}<br><small>{{ flight.landing_count }} take-offs</small>{% endif %}
                        </td>
                        <td class="text-nowrap">
                            {{ flight.type | join(" / ") | capitalize }}
                            {% if flight.activity %}<br><small>{{ flight.activity }}</small>{% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table></div>
        </div>
    </section>
{% endblock %}

rembish_org/templates/drone/new_flight.html
{% extends "layout.html" %}

{% block title %}New flight - Alex Rembish{% endblock %}

{% block css %}
  <link href="{{ static_url('vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css') }}" rel="stylesheet">
  <link href="{{ static_url('vendor/bootstrap-select/css/bootstrap-select.min.css') }}" rel="stylesheet">
  <link href="{{ static_url('vendor/bootstrap-timepicker/css/bootstrap-timepicker.min.css') }}" rel="stylesheet">
{% endblock %}

{% block js %}
  <script src="{{ static_url('vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
  <script src="{{ static_url('vendor/bootstrap-select/js/bootstrap-select.min.js') }}"></script>
  <script src="{{ static_url('vendor/bootstrap-timepicker/js/bootstrap-timepicker.min.js') }}"></script>
  <script src="{{ static_url('vendor/moment/moment.min.js') }}"></script>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key={{ config['GOOGLE_API_KEY'] }}&libraries=places&language=en&callback=initMap"></script>

    <script>
    function initMap() {
        const map = new google.maps.Map(document.getElementById("map"), {
            center: {lat: 50.08804, lng: 14.42076},  // Default position is Prague
            zoom: 13,
            mapTypeId: "roadmap",
        });
        const locationInput = document.getElementById("location");
        const searchBox = new google.maps.places.SearchBox(locationInput);
        const gps = $("#gps"), lat = $("#latitude"), lng = $("#longitude");

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition((position => {
                const latitude  = position.coords.latitude;
                const longitude = position.coords.longitude;
                map.setCenter(new google.maps.LatLng(latitude, longitude));
            }));
        }

        let markerLocation, markerPosition;

        map.addListener("bounds_changed", () => {
            searchBox.setBounds(map.getBounds());
        });

        map.addListener("dblclick", (event) => {
            if (markerPosition) {
                markerPosition.setMap(null);
            }

            const position = event.latLng;
            markerPosition = new google.maps.Marker({
                map,
                title: "Exact position",
                position: position
            });

            gps.val(position.lat() + ", " + position.lng());
            lat.val(position.lat());
            lng.val(position.lng());
        });

        searchBox.addListener("places_changed", () => {
            const place_id = $("#place_id");
            place_id.val("");

            const places = searchBox.getPlaces();
            if (places.length === 0 || !places[0].geometry) {
                return;
            }

            if (markerLocation) {
                markerLocation.setMap(null);
            }
            if (markerPosition) {
                markerPosition.setMap(null);
            }

            const place = places[0];
            const bounds = new google.maps.LatLngBounds();
            const icon = {
                url: place.icon,
                size: new google.maps.Size(71, 71),
                origin: new google.maps.Point(0, 0),
                anchor: new google.maps.Point(17, 34),
                scaledSize: new google.maps.Size(25, 25),
            };
            const placeLocation = place.geometry.location;

            markerLocation = new google.maps.Marker({
              map, icon,
              title: place.name,
              position: placeLocation,
            });
            place_id.val(place.place_id);

            gps.val(placeLocation.lat() + ", " + placeLocation.lng());
            lat.val(placeLocation.lat());
            lng.val(placeLocation.lng());

            if (place.geometry.viewport) {
                bounds.union(place.geometry.viewport);
            } else {
                bounds.extend(place.geometry.location);
            }

            map.fitBounds(bounds)
        });
    }

    let takeoffs = 0;
    $(document).ready(() => {
        $.fn.datepicker.defaults.autoclose = true;

        $.fn.timepicker.defaults.secondStep = 1;
        $.fn.timepicker.defaults.minuteStep = 1;
        $.fn.timepicker.defaults.icons = {
            up: "icofont icofont-rounded-up",
            down: "icofont icofont-rounded-down"
        };
        $.fn.timepicker.defaults.showMeridian = false;
        $.fn.timepicker.defaults.showSeconds = true;

        $(".takeoff-delete").click(function() {
            $(this).closest(".form-row").remove();
            return false;
        });
        $("#takeoff-add").click(() => {
            takeoffs++;
            let div = $("#takeoffs>div:first").clone(true, true);
            $("input", div).each((i, element) => {
                $(element).prop("id", $(element).prop("id").replace("--", "-" + takeoffs + "-"));
                $(element).prop("name", $(element).prop("id"));
            });
            div.removeClass("d-none");
            $(div).insertAfter("#takeoffs>div:last");
            return false;
        });

        $("input.tp").change(function() {
            const self = $(this);
            const row = self.closest(".form-row");

            let start = $(".tp-start", row).val();
            let duration = $(".tp-duration", row).val();
            let finish = $(".tp-finish", row).val();

            if (start && finish && self.hasClass("tp-finish")) {
                start = moment(start, "HH:mm:ss");
                finish = moment(finish, "HH:mm:ss");
                duration = moment.utc(finish.diff(start, "milliseconds"));

                $(".tp-duration", row).val(duration.format("HH:mm:ss"));
            } else if (start && duration) {
                start = moment(start, "HH:mm:ss");
                duration = moment.duration(duration);
                finish = start.add(duration, "seconds");

                $(".tp-finish", row).val(finish.format("HH:mm:ss"));
            }
        });
    });
    </script>
{% endblock %}

{% block main %}
    <section class="flightlog">
        <div class="container">
            <div class="section-title">
                <h2>Flight registration</h2>
            </div>

            <form method="post" action="{{ url_for('drone.new_flight') }}">
                {{ form.csrf_token }}
                <div class="form-row">
                    <div class="form-group col-2">
                        <div class="input-group date" data-provide="datepicker" data-date-format="dd.mm.yyyy" data-date-week-start="1">
                            {{ form.date(class_="form-control") }}
                            <div class="input-group-append">
                                <div class="input-group-text"><span class="icofont icofont-calendar"></span></div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-4">{{ form.drone_id(class_="form-control selectpicker") }}</div>
                    <div class="form-group col-3">{{ form.type(class_="form-control selectpicker") }}</div>
                </div>

                <div class="form-row">
                    <div class="form-group col">{{ form.location(class_="form-control", placeholder=form.location.label.text) }} {{ form.place_id }}</div>
                    <div class="form-group col-5">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <div class="input-group-text"><span class="icofont icofont-air-balloon"></span></div>
                            </div>
                            <input type="text" class="form-control" id="gps" required>{{ form.latitude }}{{ form.longitude }}
                        </div>
                    </div>
                </div>

                <div id="map" style="height: 300px; margin-bottom: 10px;"></div>

                <div class="form-row">
                    <div class="form-group col-2">Take-off</div>
                    <div class="form-group col-2">Duration</div>
                    <div class="form-group col-2">Landing</div>
                    <div class="form-group col-2">Distance, m</div>
                    <div class="form-group col-2">Altitude, m</div>
                    <div class="form-group col-1"><button class="btn btn-outline-dark" id="takeoff-add"><span class="icofont icofont-plus"></span></button></div>
                </div>
                <div id="takeoffs">
                    <div class="form-row d-none">
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                <input class="form-control tp tp-start" data-provide="timepicker" id="takeoffs--start" type="text" value="">
                            </div>
                        </div>
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                <input class="form-control tp tp-duration" data-default-time="false" data-max-hours="2" data-provide="timepicker" id="takeoffs--duration" type="text" value="">
                            </div>
                        </div>
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                <input id="takeoffs--finish" type="text" class="form-control tp tp-finish" data-provide="timepicker">
                            </div>
                        </div>
                        <div class="form-group col-2"><input class="form-control" id="takeoffs--distance" type="number" value="" min="0"></div>
                        <div class="form-group col-2"><input class="form-control" id="takeoffs--altitude" type="number" value=""></div>
                        <div class="form-group col-1"><button class="btn btn-outline-danger takeoff-delete"><span class="icofont icofont-trash"></span></button></div>
                    </div>
                {% for takeoff in form.takeoffs %}
                    <div class="form-row">
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                {{ takeoff.start(class_="form-control tp tp-start", data_provide="timepicker") }}
                            </div>
                        </div>
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                <input class="form-control tp tp-duration" data-default-time="false" data-max-hours="2" data-provide="timepicker" id="takeoffs-{{ loop.index0 }}-duration" name="takeoffs-{{ loop.index0 }}-duration" type="text" value="">
                            </div>
                        </div>
                        <div class="form-group col-2">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><span class="icofont icofont-clock-time"></span></div>
                                </div>
                                {{ takeoff.finish(class_="form-control tp tp-finish", data_provide="timepicker") }}
                            </div>
                        </div>
                        <div class="form-group col-2">{{ takeoff.distance(class_="form-control", min=0) }}</div>
                        <div class="form-group col-2">{{ takeoff.altitude(class_="form-control") }}</div>
                        <div class="form-group col-1"><button class="btn btn-outline-danger takeoff-delete"><span class="icofont icofont-trash"></span></button></div>
                    </div>
                {% endfor %}
                </div>

                <div class="form-row"><div class="form-group col">{{ form.activity(class_="form-control", placeholder=form.activity.label.text) }}</div></div>
                <div class="form-row"><div class="form-group col">{{ form.description(class_="form-control", placeholder=form.description.label.text) }}</div></div>

                {{ form.register(class_="form-control") }}
            </form>
        </div>
    </section>
{% endblock %}